// <auto-generated />
using System;
using GreenFantasiaGifts011.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenFantasiaGifts011.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260106113454_AddDescriptionToProductsTable")]
    partial class AddDescriptionToProductsTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenFantasiaGifts011.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "",
                            Category = "Indoor Plants",
                            CreatedAt = new DateTime(2026, 1, 6, 11, 34, 54, 201, DateTimeKind.Utc).AddTicks(3458),
                            Description = "The ultimate air-purifying indoor palm. This elegant plant features feathery fronds that add a tropical feel to any room. It thrives in bright, indirect light and is safe for pets.",
                            ImageUrl = "/images/ArecaPalm.png",
                            IsInStock = true,
                            Name = "Areca Palm",
                            Price = 20.00m,
                            Specification = ""
                        },
                        new
                        {
                            Id = 2,
                            Caption = "",
                            Category = "Tropical Plants",
                            CreatedAt = new DateTime(2026, 1, 6, 11, 34, 54, 201, DateTimeKind.Utc).AddTicks(3595),
                            Description = "A dramatic tropical plant known for its large, banana-like leaves and stunning flowers. It requires bright light and space to grow, making it a perfect statement piece for large living areas.",
                            ImageUrl = "/images/BirdOfParadise.png",
                            IsInStock = true,
                            Name = "Bird of Paradise",
                            Price = 10.00m,
                            Specification = ""
                        },
                        new
                        {
                            Id = 3,
                            Caption = "",
                            Category = "Low Light Plants",
                            CreatedAt = new DateTime(2026, 1, 6, 11, 34, 54, 201, DateTimeKind.Utc).AddTicks(3597),
                            Description = "Vertical, sleek, and nearly indestructible. Perfect for beginners, the Snake Plant can survive in low light conditions and needs very little water. It's also famous for converting CO2 into oxygen at night.",
                            ImageUrl = "/images/SnakePlant.png",
                            IsInStock = true,
                            Name = "Snake Plant",
                            Price = 5.00m,
                            Specification = ""
                        },
                        new
                        {
                            Id = 4,
                            Caption = "",
                            Category = "Indoor Trees",
                            CreatedAt = new DateTime(2026, 1, 6, 11, 34, 54, 201, DateTimeKind.Utc).AddTicks(3598),
                            Description = "Stunning glossy dark green foliage. The Ficus elastica prefers bright, filtered light. Its broad leaves act as natural dust magnets, helping to clean the air while adding a sophisticated look to your office.",
                            ImageUrl = "/images/RubberPlant.png",
                            IsInStock = true,
                            Name = "Rubber Plant",
                            Price = 13.00m,
                            Specification = ""
                        },
                        new
                        {
                            Id = 5,
                            Caption = "",
                            Category = "Low Light Plants",
                            CreatedAt = new DateTime(2026, 1, 6, 11, 34, 54, 201, DateTimeKind.Utc).AddTicks(3600),
                            Description = "Tough and low maintenance. This variety survives in very low light and needs little water. Its unique variegated patterns make it a visually striking addition to any dark corner.",
                            ImageUrl = "/images/DracaenaTrifasciata.png",
                            IsInStock = true,
                            Name = "Dracaena Trifasciata",
                            Price = 9.00m,
                            Specification = ""
                        });
                });

            modelBuilder.Entity("GreenFantasiaGifts011.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "NON@greenfantasia.com",
                            Password = "NON6675",
                            Role = "Admin",
                            Username = "AdminGreen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
