// <auto-generated />
using System;
using GreenFantasiaGifts011.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GreenFantasiaGifts011.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260105230327_InitialFix011")]
    partial class InitialFix011
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GreenFantasiaGifts011.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Caption")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInStock")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Specification")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Caption = "The ultimate air-purifying indoor palm.",
                            Category = "Indoor Plants",
                            CreatedAt = new DateTime(2026, 1, 5, 23, 3, 27, 86, DateTimeKind.Utc).AddTicks(4910),
                            ImageUrl = "/images/ArecaPalm.png",
                            IsInStock = true,
                            Name = "Areca Palm",
                            Price = 120.00m,
                            Specification = "Thrives in bright, indirect light."
                        },
                        new
                        {
                            Id = 2,
                            Caption = "A dramatic tropical plant.",
                            Category = "Tropical Plants",
                            CreatedAt = new DateTime(2026, 1, 5, 23, 3, 27, 86, DateTimeKind.Utc).AddTicks(5000),
                            ImageUrl = "/images/BirdOfParadise.png",
                            IsInStock = true,
                            Name = "Bird of Paradise",
                            Price = 250.00m,
                            Specification = "Requires bright light and space to grow."
                        },
                        new
                        {
                            Id = 3,
                            Caption = "Vertical, sleek, and nearly indestructible.",
                            Category = "Low Light Plants",
                            CreatedAt = new DateTime(2026, 1, 5, 23, 3, 27, 86, DateTimeKind.Utc).AddTicks(5002),
                            ImageUrl = "/images/SnakePlant.png",
                            IsInStock = true,
                            Name = "Snake Plant",
                            Price = 45.00m,
                            Specification = "Perfect for beginners. Low light tolerant."
                        },
                        new
                        {
                            Id = 4,
                            Caption = "Stunning glossy dark green foliage.",
                            Category = "Indoor Trees",
                            CreatedAt = new DateTime(2026, 1, 5, 23, 3, 27, 86, DateTimeKind.Utc).AddTicks(5004),
                            ImageUrl = "/images/RubberPlant.png",
                            IsInStock = true,
                            Name = "Rubber Plant",
                            Price = 85.00m,
                            Specification = "Ficus elastica. Prefers bright, filtered light."
                        },
                        new
                        {
                            Id = 5,
                            Caption = "Tough and low maintenance.",
                            Category = "Low Light Plants",
                            CreatedAt = new DateTime(2026, 1, 5, 23, 3, 27, 86, DateTimeKind.Utc).AddTicks(5005),
                            ImageUrl = "/images/DracaenaTrifasciata.png",
                            IsInStock = true,
                            Name = "Dracaena Trifasciata",
                            Price = 55.00m,
                            Specification = "Survives in very low light and needs little water."
                        });
                });

            modelBuilder.Entity("GreenFantasiaGifts011.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "NON@greenfantasia.com",
                            Password = "NON6675",
                            Role = "Admin",
                            Username = "AdminGreen"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
